style.css

Make text responsive

---

style.css

- `Get Started` button was not responsive.
Closes: #22 
Made Get started button responsive for different screen sizes.
Breakpoints introduced ;- `600px` `768px` `1000px`
NA
1. <1000px
2. <768px
3. <600px

Made get Started button responsive

---

style.css

- navbar is not responsive for mobile
Closes: #29 
Make navbar look good in mobile devices 
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!
- make navbar mobile responstive
make navbar center for mobile devices and also match the color og hover button with you all over website

navbar mobile responsive

---

index.html
style.css

Designed Scrollbar and Added padding between headings
Closes: #45
- Design scrollbar
- Added padding and margin to make UI clean (check screenshots)

Designed scrollbar and added padding

---

index.html
main.js
style.css

Closes: #47 
Added toggle button to the website.
Added html code for toggle button in index.html and added CSS code in style.css.
Created main.js file to include javascript code  and script tag is added into index.html.
- [ x] My code follows the style guidelines of this project.
- [x ] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.

Added dark theme toggle button

---

index.html
scroll.js

- Added Animate elements as they scroll into view 
Closes: #[58]
Added Animate elements as they scroll into view  features while scrolling the site 
NA
https://user-images.githubusercontent.com/41264611/193884209-a4cc4fa9-2a81-45e9-8028-9501ae833d50.mp4

Added scrollReveal library

---

style.css

A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

Update the right navbar button

---

index.html
style.css

- Animation Effect on hover web-x
Closes: #43 
I create a animation in style.css so when you hover the web-x than you see the web-x logo moving in 360deg and in bakground planet and stars are moving 
If any unusual behaviour simple follow these steps      **.nav-area .left-nav a:hover**  -->  delete  -->   animation-name: example;
- [x ] I have performed a self-review of my own code.

Animation Effect on hover web-x

---

index.html

Follow Us Buttons
Closes: #63 
Added relevant links to the Follow Us Buttons.
NA

Added relevant links to the Follow us Buttons

---

index.html
scroll.js
style.css

- Webiste not responsive at certain breakpoints
Closes: #62 
Added bootstrap cards and breakpoints.
NA

make website responsive in tablets

---

index.html

- The page didn't scroll to the Contact Form
Closes: #76 
Added id to the Contact form div
NA
NA

Added scrolling to the Contact Form

---

README.md

- Screenshots of the working Application in README.md were broken 
Closes: #83
I changed the screenshot src URL to the appropriate one
NA
none

Fix image address in README.md 

---

.github/labeler.yml
.github/workflow/labeler.yml

- https://github.com/yashikabhargava/WebX/issues/33
Closes: #33 
Add YML file to the auto label in issue/pr based on keyword match in the title, body, or both.
NA

Add yml file to auto label on pr/issues based on keywords on their title and body eg: hacktoberfest-accepted

---

index.html
public/contact.html
public/content/colors.html
public/content/css-generators.html
public/content/fonts.html
public/content/icons.html
public/content/stock-photos.html
public/content/template.html
public/content/ui-illustrations.html
public/content/ui-ux-designs.html
public/content/web-design-inspiration.html
public/resources.html
src/scripts/main.js
src/styles/style.css

The toggle button was not working and the other pages doesn't have the dark mode button.
Closes: #89 
I've fixed the dark mode not working in the landing page. I also added the dark mode toggle to all pages and made it functional.
(NOTE : In previous PR I have added the individual dark mode event listener scripts into their respective htmls. I've tried to add them into main.js but it was showing errors so I put them into individual pages . But there was many redundant scripts so  I closed the PR and created a new branch and only added the contact page's event listener into the html and now other pages can access the event listeners via main.js )
A clear and concise …

Fixed the Dark mode (issue #89)

---

index.html

- Favicon not displaying
Closes: #104 
Fixed the link tag for the favicon, it had the wrong image path.
NA

Fixed Favicon Path

---

src/styles/style.css

- Logo flickering
Removed the code that was creating flickering issue while hovering on logo.
NA
- [X ] I have commented my code, particularly in hard-to-understand areas.

logo flickering issue solved

---

index.html

Closes: #106 
Added proper styling so that the landing text is not covered by social icons while keeping the same look of the website in mind so it doesn't change.
NA

Fixed the landing page's text covered by social icons

---

public/resources.html

- The path to the index.html file is not set correctly in resources.html.
Changed the path in resources.html page.
NA
https://user-images.githubusercontent.com/63171580/195680091-317fb5c7-d917-4732-a574-0e5ab2a2e7eb.mov

path changed in resources html file

---

index.html
public/contact.html
public/content/colors.html
public/content/css-generators.html
public/content/fonts.html
public/content/icons.html
public/content/learn-web-dev.html
public/content/prototyping.html
public/content/stock-photos.html
public/content/ui-illustrations.html
public/content/ui-ux-designs.html
public/content/web-design-inspiration.html
public/resources.html

- Meta tags were same for all the pages.
Closes: #99 
Change titles of each page and added description meta tags to each page.
NA

meta tags added for each page

---

src/styles/style.css

In dark mode background is not changing and resource button color is white
After fixing

Fixed dark mode background-color and resource btn color

---

public/content/colors.html
public/content/css-generators.html
public/content/fonts.html
public/content/icons.html
public/content/learn-web-dev.html
public/content/prototyping.html
public/content/stock-photos.html
public/content/template.html
public/content/ui-illustrations.html
public/content/ui-ux-designs.html
public/content/web-design-inspiration.html

- Path to index.html file not set correctly in logo for all resources page.
Closes: #124 
Added correct path to index.html file.
NA
https://user-images.githubusercontent.com/63171580/196528922-cd9b8fec-1636-4b01-a2a2-f4f5d5a85968.mov

broken links fixed

---

public/contact.html
src/scripts/validator.js

Input verification was earlier implemented with a simple isNumeric check using regular expressions. This was not suitable for country-specific verification of phone numbers. Therefore, new input verification was added, allowing the user to select the country and verify across multiple country-specific extensions, both mobiles and landlines. 
Closes: #122 
No new files added. 
Code addition to src/scripts/validation.js and contact.html 
The International Telephone Input plugin was used to add the necessary functionality. Documentation can be found [here](https://github.com/jackocnr/intl-tel-input).
NA

added phone number verification with country selector

---

index.html
public/resources.html

I have added a tab in the navbar called contribute which redirects the user to the github page.
I have added a tab in the navbar called contribute which redirects the user to the github page.
NA

Adding contribute tab in navbar

---

index.html
public/resources.html

Fixed the broken image in prototyping tools
Fixed the broken image in prototyping tools by fixing the image path

Fixed the broken image in prototyping tools

---

index.html
public/resources.html

Some of the alt text values had typos and some didnt have a proper alt text. I have changed it to a proper one
Some of the alt text values had typos and some didnt have a proper alt text. I have changed it to a proper one

Fixing the typos in alt text 

---

index.html
public/resources.html

Added a new resource to learn Web development
Added a new resource to learn Web development. JavaTpoint is free website to learn about html, CSS, Javascript
NA

Added a new resource to learn Web development

---

src/styles/style.css

- Text-decoration
Closes: #[141]
NA

#141 Fixed Text-decoration

---

index.html
public/contact.html
public/resources.html
src/styles/style.css

Closes: #[143]
I've fixed the dark mode toggle in the Navbar which makes it look a lot better. Please do check this out and merge.
No

143 Dark Mode toggle fixed

---

public/content/colors.html
public/content/css-generators.html
public/content/fonts.html
public/content/icons.html
public/content/stock-photos.html
public/content/ui-illustrations.html
public/content/ui-ux-designs.html
public/content/web-design-inspiration.html
src/styles/style.css

Closes: #149 
i added a class to the navbar of the icons page which fix the issue and added some margins so that page wont distort

fixed the dropdown bug in icons page

---

src/styles/style.css

Fixed the resource button when clicking the button it was giving the uneven box shadow 
After fixing

fix in resources button
